@port = 3333
@baseUrl = http://localhost

@host = {{baseUrl}}:{{port}}
@ws_host = ws://localhost:{{port}}

###
# Get poll info
# @name getPolls
GET {{host}}/polls/clseqmccs00005odpe3rmh98j

###
# Get poll info
# @name getPollResults
GET {{ws_host}}/polls/clseqmccs00005odpe3rmh98j/results

###
# Create Poll
# @name createPoll
POST {{host}}/polls
Content-type: application/json

{
  "title": "Qual o melhor micro-framework Node.js?",
  "options": ["Express", "Fastify"]
}

###
# Vote on Poll
# @name voteOnPoll
POST {{host}}/polls/clseqmccs00005odpe3rmh98j/votes
Content-type: application/json

{
  "poll_option_id": "clseqmccs00025odpq2hggmy2"
}